---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: demo
  name: demo
  namespace: default
  selfLink: /apis/extensions/v1beta1/namespaces/default/deployments/demo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: demo
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: demo
        version: BUILD_VERSION
    spec:
      containers:
      - env:
        - name: GOOGLE_APPLICATION_CREDENTIALS
          value: /tmp/credentials/sa.json
        - name: MODEL_NAME #Change this
          value: model.pkl
        - name: GCS_MODEL_BUCKET #Change this
          value: generic-model
        image: MODEL_IMAGE_NAME
        imagePullPolicy: IfNotPresent
        name: github-agnnn-models
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /tmp/credentials
          name: google-cloud-key
          readOnly: true
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - name: google-cloud-key
        secret:
          defaultMode: 420
          secretName: credentials
---
apiVersion: v1
kind: "Service"
metadata:
  name: "demo"
  labels:
    app: "demo"
  namespace: "default"
spec:
  type: "LoadBalancer"
  sessionAffinity: "None"
  externalTrafficPolicy: "Cluster"
  ports:
  - port: 80
    targetPort: 5000
    protocol: "TCP"
  selector:
    app: "demo"
status:
  loadBalancer: {}
